version: "3"

services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5673:5672"

  worker:
    build: .
    command: celery -A celery_worker worker -l info
    volumes:
      - .:/code
    depends_on:
      - rabbit
      - db

  celery-beat:
    build: .
    command: celery -A celery_worker beat -l info
    volumes:
      - .:/code
    depends_on:
      - rabbit
      - db

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bank_db

  web:
    build: .
    command: bash -c "alembic upgrade head && uvicorn view:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
